"""Adding user table

Revision ID: ea12725f6d71
Revises: f9a0445151f0
Create Date: 2023-09-18 22:22:30.730294

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea12725f6d71'
down_revision: Union[str, None] = 'f9a0445151f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('identifier', sa.Integer(), nullable=False))
    op.add_column('users', sa.Column('first_name', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('last_name', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('username', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('is_bot', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('language_code', sa.String(length=10), nullable=True))
    op.add_column('users', sa.Column('is_premium', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('phone_number', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('create_on', sa.TIMESTAMP(), nullable=False))
    op.add_column('users', sa.Column('update_on', sa.TIMESTAMP(), nullable=False))
    op.create_unique_constraint(None, 'users', ['identifier'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'update_on')
    op.drop_column('users', 'create_on')
    op.drop_column('users', 'phone_number')
    op.drop_column('users', 'is_premium')
    op.drop_column('users', 'language_code')
    op.drop_column('users', 'is_bot')
    op.drop_column('users', 'username')
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'first_name')
    op.drop_column('users', 'identifier')
    # ### end Alembic commands ###
