filename = 'bot.log'
directory = 'logs'
logger_level = 'DEBUG'
logger_format = '{time:YYYY-MM-DD HH:mm:ss} | {level} | {name} | file:{file} | line:{line} - {message}'
logger_rotation = '300 MB'
logger_compression = 'zip'
